### ISSUE TITLE
Error trying to create a new server

### ISSUE THREAD

**Issue by ValentijnDevelopment** [mattmalec/Pterodactyl4J#3]
Hi, I get this error while creating a server and I already auto-configure command:

How can I fix this?

Exception in thread "main" com.mattmalec.pterodactyl4j.exceptions.HttpException: Pterodactyl4J has encountered a 400 error.

	- No nodes satisfying the requirements specified for automatic deployment could be found.

	at com.mattmalec.pterodactyl4j.requests.Requester.request(Requester.java:71)
	at com.mattmalec.pterodactyl4j.application.entities.impl.CreateServerImpl$1.execute(CreateServerImpl.java:211)
	at com.mattmalec.pterodactyl4j.application.entities.impl.CreateServerImpl$1.execute(CreateServerImpl.java:174)

**Comment by fayeinmay** [comment]
This is not a problem of the library, but as the error states you don't have any nodes satisfying the requirements of that request.
