### ISSUE TITLE
NullPointerException flood 

### ISSUE THREAD

**Issue by JacobPassam** [mattmalec/Pterodactyl4J#39]
My program hadn't had any activity for about 6 hours. I come to check the console output 12 hours later and it's flooded, a few hundred times, with:

```
Aug 14 00:39:00 ns527849 java[2658538]: java.lang.NullPointerException: Cannot invoke "java.io.InputStream.read(byte[])" because "this.body" is null
Aug 14 00:39:00 ns527849 java[2658538]:         at com.mattmalec.pterodactyl4j.requests.Response.getRawObject(Response.java:76)
Aug 14 00:39:00 ns527849 java[2658538]:         at com.mattmalec.pterodactyl4j.requests.Response.getObject(Response.java:98)
Aug 14 00:39:00 ns527849 java[2658538]:         at com.mattmalec.pterodactyl4j.requests.Request.setOnFailure(Request.java:81)
Aug 14 00:39:00 ns527849 java[2658538]:         at com.mattmalec.pterodactyl4j.requests.PteroActionImpl.handleResponse(PteroActionImpl.java:145)
Aug 14 00:39:00 ns527849 java[2658538]:         at com.mattmalec.pterodactyl4j.requests.Request.handleResponse(Request.java:145)
Aug 14 00:39:00 ns527849 java[2658538]:         at com.mattmalec.pterodactyl4j.requests.Requester.execute(Requester.java:160)
Aug 14 00:39:00 ns527849 java[2658538]:         at com.mattmalec.pterodactyl4j.requests.Requester.execute(Requester.java:63)
Aug 14 00:39:00 ns527849 java[2658538]:         at com.mattmalec.pterodactyl4j.requests.Requester.execute(Requester.java:59)
Aug 14 00:39:00 ns527849 java[2658538]:         at com.mattmalec.pterodactyl4j.requests.RateLimiter.run(RateLimiter.java:147)
Aug 14 00:39:00 ns527849 java[2658538]:         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
Aug 14 00:39:00 ns527849 java[2658538]:         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
Aug 14 00:39:00 ns527849 java[2658538]:         at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
Aug 14 00:39:00 ns527849 java[2658538]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
Aug 14 00:39:00 ns527849 java[2658538]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
Aug 14 00:39:00 ns527849 java[2658538]:         at java.base/java.lang.Thread.run(Thread.java:831)
```

No program/WS activity caused this to happen, it just happened out of nowhere and killed the program. I'm using version 2.BETA_74 on Ubuntu with pterodactyl version 1.5.1.

**Comment by mattmalec** [comment]
It could be a bad response from the panel, especially for keeping a connection open for that length of time. Has it happened every 12 hours or just a one-off thing?

**Comment by JacobPassam** [comment]
It was just a one-off thing. I've setup a cron to restart the program every 24 hours and it seems to be working alright now.
