### ISSUE TITLE
ClientEgg.EggVariable getServerValue() is not a string

### ISSUE THREAD

**Issue by AoElite** [mattmalec/Pterodactyl4J#49]
```java
   for (ClientEgg.EggVariable variable : client.retrieveServerByIdentifier("dd522d20").execute().getEgg().getVariables()) {
            String name = variable.getName();
            String env = variable.getEnvironmentVariable();
            String value = variable.getServerValue();
            System.out.println(name + " : " + env + " : " + value);
        }
```
```
Exception in thread "main" org.json.JSONException: JSONObject["server_value"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:721)
	at com.mattmalec.pterodactyl4j.client.entities.impl.ClientEggVariableImpl.getServerValue(ClientEggVariableImpl.java:53)
	at com.aoelite.me.Main.main(Main.java:27) // <-- variable.getServerValue()
```

**Comment by mattmalec** [comment]
This is fixed in version `2.BETA_118`
